include $(CLEAR_VARS)
LOCAL_MODULE := SystemWebView
LOCAL_MODULE_CLASS := APPS
LOCAL_PRODUCT_MODULE := true
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_OVERRIDES_PACKAGES := webview
LOCAL_MODULE_TARGET_ARCH := arm64
LOCAL_SRC_FILES := SystemWebView_arm64.apk
include $(BUILD_PREBUILT)
